### PR TITLE
Remove upsolete versionist files and replace with versionbot meta-data

### PR DESCRIPTION
**Pull request by alexgg**
* Remove legacy versionist.conf.js and package.json
* Add a versionbot repo.yml file and a CHANGELOG.yml

Change-type: none
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Review by nazrhom — APPROVED** [review]

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@alexgg, Looks good to me, and we already have an approval, but it looks like we're still waiting on Jenkins. Any idea what the holdup is?

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins ok to test

**Pull request merged**
