### PR TITLE
Remove dependent-devices folder

### PR DESCRIPTION
**Pull request by alexgg**
This is not a current product feature.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

cc: @rahul-thakoor just checking, these `dependat-devices` have nothing to do with the dependant devices project, right?

### CODE REVIEW

**Comment by rahul-thakoor** [comment]
doesn't look like it @alexgg

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Comment by mtoman** [comment]
@balena-ci rebase

**Pull request merged**
