### PR TITLE
yocto-linux: Update to v6.1.35

### PR DESCRIPTION
**Pull request by alexgg**
Relates-to: https://github.com/balena-os/meta-balena/pull/3179

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by klvnptr** [comment]
we would be happy to test this out if jenkins succeeds. we are migrating from intel to generic on all of our devices.

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
Requires https://github.com/balena-os/balena-generic/pull/260

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
Needs https://github.com/balena-os/meta-balena/pull/3202 for the generic-aarch64 build to pass

**Comment by acostach** [comment]
@klvnptr the v3.1.1+rev1 image is now available in balena-cloud for the Generic X86_64 (GPT)

**Comment by klvnptr** [comment]
Thanks so much @acostach Highly appreciate it. We get started testing tomorrow.

**Pull request merged**
