### PR TITLE
balena-yocto-scripts: Update to v1.17.10

### PR DESCRIPTION
**Pull request by ab77**
Update balena-yocto-scripts from v1.17.0 to v1.17.10

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.17.10
Signed-off-by: Anton Belodedenko <anton@balena.io>

### CODE REVIEW

**Comment by ab77** [comment]
> Embedded changelogs don't work correctly if the commit body includes the `v` prefixes IIRC.

I just copied Alex's previous commit..

**Review by klutchell — APPROVED** [review]
lgtm

**Comment by klutchell** [comment]
right you are, and the embedded changelog seems to have worked in that case so you're good to go

**Comment by klutchell** [comment]
@resin-jenkins test this please

**Pull request merged**
