### PR TITLE
Kirkstone

### PR DESCRIPTION
**Pull request by jakogut**
~~This may fail to build before https://github.com/balena-os/meta-balena/pull/2788 is merged~~

Tested w/ generic-amd64 as well as generic-aarch64:
```
root@572aaf5:~# uname -a
Linux 572aaf5 5.15.62-yocto-standard #1 SMP Mon Aug 22 15:16:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

### CODE REVIEW

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
generic-amd64: HUP test is failing, OS/cloud are passing.

**Pull request merged**
